Onboarding with styles
sandboxnu/flow-in-the-field pull request #41
Opened 2021-11-04 18:25 UTC by koulopoulos

* Added bullet points to 'how it works' onboarding screen.
* Added register button styling on final onboarding screen
* Changed register button route from `signInFlow` to `login`

2021-11-04 21:11 UTC, emaela requested changes
I have a small phone and so the font is a bit too big. Ideally the font size would be responsive to the screen size, but for now I think it would be sufficient to just make the font a little smaller, like 18px to match the Figma wireframes. I'll make a separate ticket for responsive font size.

![IMG_3923](https://user-images.githubusercontent.com/25839028/140420413-44fd8532-c7ea-45a8-947d-3133e7f085af.PNG)

2021-11-05 01:02 UTC, koulopoulos commented on src/screens/Onboarding/OnboardingScreen.tsx
> +        <TouchableHighlight style={styles.touchable}>
This was a remnant from before the Swiper was implemented. I'll remove it in the next commit.

2021-11-05 02:06 UTC, koulopoulos commented
The latest commit should have fixed the issue with the font.

Additionally, I spent some time cleaning up the onboarding code. One **major change** I made was to remove the `FinalOnboardingScreen.tsx` and add an optional navigation button (register button) to `OnboardingScreen.tsx`. This avoids unnecessary code duplication between `OnboardingScreen.tsx` and `FinalOnboardingScreen.tsx`, and simplifies the code base.

2021-11-05 18:09 UTC, emaela approved these changes
Looks good, thanks for cleaning it up!

2021-11-05 18:39 UTC, merged