64 back buttons
sandboxnu/flow-in-the-field pull request #71
Opened 2021-11-29 23:41 UTC by ofloody

close #64

2021-11-29 23:41 UTC, jrosen081 commented
@ofloody You probably want to make this point to the `dev` branch, not the `main` branch

2021-11-30 00:59 UTC, emaela requested changes
It seems like removing the drawer navigation got rid of the flow logo from the screens, but we want to keep that. 
I also noticed that the header has a border and that the background of the screen content is gray. Would it be possible to update the styling to match the wireframes, so that we have the whole screen's background be white and have no border between the header and content?

We will eventually be restyling the back button, but I think that react navigation lets you customize the back button image, so I'm not too worried about that. 

Sidenote: the PR will need to be updated to merge into dev instead of main

2021-11-30 22:08 UTC, emaela commented on frontend/App.tsx
> +*/
Can we remove this commented code?

2021-12-02 01:07 UTC, emaela approved these changes

2021-12-02 01:10 UTC, merged